<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use App\Modules\Connectors\Models\JobInstance;
use App\Modules\Operations\Models\Reimbursement;
use App\Modules\Operations\Models\ReimbursementAttachment;
use App\Modules\Core\Auditing\Services\UapLogger;
use Carbon\Carbon;

class CleanupUnusedUploadsCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'uploads:cleanup {--hours=24 : Retention threshold in hours for unlinked temporary files and deleted entity storage}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Periodically clean up unused uploaded files and storage folders linked to deleted database entities (batch jobs, discovery temp, provisioning temp, reimbursement proofs & inputs).';

    public function handle(): int
    {
        $hours = (int) $this->option('hours');
        $cutoffTime = Carbon::now()->subHours($hours)->getTimestamp();

        $this->info("Starting system storage cleanup for unlinked uploads and deleted entity folders (Threshold: >{$hours}h)...");

        $batchTempDeleted          = $this->cleanupBatchTempFiles($cutoffTime);
        $provisioningTempDeleted   = $this->cleanupProvisioningTempFiles($cutoffTime);
        $orphanedJobFoldersDeleted = $this->cleanupOrphanedJobDirectories($cutoffTime);
        $attachmentsDeleted        = $this->cleanupOrphanedProofAttachments($cutoffTime);
        $reimbursementInputsDeleted = $this->cleanupOrphanedReimbursementInputs($cutoffTime);

        $summary = [
            'batch_discovery_temp_deleted'  => $batchTempDeleted,
            'provisioning_temp_deleted'     => $provisioningTempDeleted,
            'orphaned_job_folders_deleted'  => $orphanedJobFoldersDeleted,
            'orphaned_proofs_deleted'       => $attachmentsDeleted,
            'orphaned_inputs_deleted'       => $reimbursementInputsDeleted,
            'cutoff_hours'                  => $hours,
        ];

        UapLogger::info('SystemCleanup', 'UNUSED_FILES_CLEANUP_COMPLETED', $summary);

        $this->info("Cleanup completed successfully!");
        $this->table(['Storage Category', 'Items Removed'], [
            ['Batch Discovery Temp Files', $batchTempDeleted],
            ['Provisioning Temp Batch Files', $provisioningTempDeleted],
            ['Orphaned Job Directories (jobs/{id})', $orphanedJobFoldersDeleted],
            ['Orphaned Proof Attachments', $attachmentsDeleted],
            ['Orphaned Reimbursement Inputs', $reimbursementInputsDeleted],
        ]);

        return Self::SUCCESS;
    }

    /**
     * Clean up orphaned batch execution folders (jobs/{instance_id}) whose JobInstance model is deleted.
     */
    protected function cleanupOrphanedJobDirectories(int $cutoffTime): int
    {
        $deletedCount = 0;
        $disk = Storage::disk('local');
        $basePath = config('connectors.batch.storage_path', 'jobs');

        if (!$disk->exists($basePath)) {
            return 0;
        }

        // Retrieve all existing JobInstance IDs from the DB
        $existingJobInstanceIds = JobInstance::pluck('id')->toArray();

        // Get all subdirectories inside 'jobs/'
        $directories = $disk->directories($basePath);

        foreach ($directories as $dirPath) {
            $instanceId = basename($dirPath);

            // Skip if the job instance still exists in the database
            if (in_array($instanceId, $existingJobInstanceIds)) {
                continue;
            }

            // Delete the orphaned folder if last modified is older than cutoff
            if ($disk->lastModified($dirPath) < $cutoffTime) {
                if ($disk->deleteDirectory($dirPath)) {
                    $deletedCount++;
                }
            }
        }

        return $deletedCount;
    }

    /**
     * Clean up temporary batch provisioning files generated by BulkProvisioningBuilder in 'temp/batch/'.
     */
    protected function cleanupProvisioningTempFiles(int $cutoffTime): int
    {
        $deletedCount = 0;
        $disk = Storage::disk('local');
        $directory = 'temp/batch';

        if (!$disk->exists($directory)) {
            return 0;
        }

        $files = $disk->files($directory);

        foreach ($files as $file) {
            if ($disk->lastModified($file) < $cutoffTime) {
                if ($disk->delete($file)) {
                    $deletedCount++;
                }
            }
        }

        return $deletedCount;
    }

    /**
     * Clean up temporary batch discovery files in 'temp/batch_discovery/'.
     */
    protected function cleanupBatchTempFiles(int $cutoffTime): int
    {
        $deletedCount = 0;
        $disk = Storage::disk('local');
        $directory = 'temp/batch_discovery';

        if (!$disk->exists($directory)) {
            return 0;
        }

        $files = $disk->files($directory);

        foreach ($files as $file) {
            if ($disk->lastModified($file) < $cutoffTime) {
                if ($disk->delete($file)) {
                    $deletedCount++;
                }
            }
        }

        return $deletedCount;
    }

    /**
     * Clean up orphaned reimbursement proof attachments in 'reimbursement_attachments' disk.
     */
    protected function cleanupOrphanedProofAttachments(int $cutoffTime): int
    {
        $deletedCount = 0;
        $disk = Storage::disk('reimbursement_attachments');

        if (!$disk->exists('')) {
            return 0;
        }

        // Active attachment filenames in DB
        $registeredFiles = ReimbursementAttachment::pluck('file_path')
            ->filter()
            ->map(fn($path) => basename($path))
            ->toArray();

        $allDiskFiles = $disk->files('');

        foreach ($allDiskFiles as $file) {
            $filename = basename($file);

            if (in_array($filename, $registeredFiles)) {
                continue;
            }

            if ($disk->lastModified($file) < $cutoffTime) {
                if ($disk->delete($file)) {
                    $deletedCount++;
                }
            }
        }

        return $deletedCount;
    }

    /**
     * Clean up orphaned input sheets in 'secure_reimbursements' disk under 'uploaded_sheets/'.
     */
    protected function cleanupOrphanedReimbursementInputs(int $cutoffTime): int
    {
        $deletedCount = 0;
        $disk = Storage::disk('secure_reimbursements');
        $directory = 'uploaded_sheets';

        if (!$disk->exists($directory)) {
            return 0;
        }

        // Active file_reference_ids in DB
        $activeReferences = Reimbursement::whereNotNull('file_reference_id')
            ->pluck('file_reference_id')
            ->toArray();

        $allDiskFiles = $disk->files($directory);

        foreach ($allDiskFiles as $file) {
            $filename = pathinfo($file, PATHINFO_FILENAME); // e.g., VLT-REF-XXXXX

            if (in_array($filename, $activeReferences)) {
                continue;
            }

            if ($disk->lastModified($file) < $cutoffTime) {
                if ($disk->delete($file)) {
                    $deletedCount++;
                }
            }
        }

        return $deletedCount;
    }
}