<?php

return [
    /*
    |--------------------------------------------------------------------------
    | UCIP Protocol Fault Codes (XML-RPC Level)
    |--------------------------------------------------------------------------
    */
    'faults' => [
        1000 => 'Illegal request message',
        1001 => 'Mandatory field missing',
        1002 => 'Illegal data type',
        1003 => 'Data out of bounds',
        1004 => 'Unknown operation',
        1005 => 'Internal server error',
        1007 => 'Overload rejection',
    ],

   /*
    |--------------------------------------------------------------------------
    | UCIP Application Response Codes
    |--------------------------------------------------------------------------
    */
    'responses' => [

        // Success Codes
        0   => 'Successful',
        1   => 'Ok but supervision period exceeded',
        2   => 'Ok but service fee period exceeded',
        3   => 'Subscriber already on destinationSDP',
        4   => 'Subscriber move successful but subscriber may be in sleep mode',
        5   => 'Refill performed successful but PAM trigger unsuccessful',

        // General Errors
        100 => 'Other Error',
        101 => 'Not used',
        102 => 'Subscriber not found',
        103 => 'Account barred from refill',
        104 => 'Temporary blocked',
        105 => 'Dedicated account not allowed',
        106 => 'Dedicated account negative',
        107 => 'Voucher status used by same',
        108 => 'Voucher status used by different',
        109 => 'Voucher status unavailable',
        110 => 'Voucher status expired',
        111 => 'Voucher status stolen or missing',
        112 => 'Voucher status damaged',
        113 => 'Voucher status pending',
        114 => 'Voucher type not accepted',
        115 => 'Refill not accepted',
        117 => 'Service class change not allowed',
        119 => 'Invalid voucher activation code',
        120 => 'Invalid refill profile',
        121 => 'Supervision period too long',
        122 => 'Service fee period too long',
        123 => 'Max credit limit exceeded',
        124 => 'Below minimum balance',
        126 => 'Account not active',
        127 => 'Accumulator not available',
        128 => 'Invalid PIN code',
        129 => 'FaF number does not exist',
        130 => 'FaF number not allowed (see notAllowedReason)',
        133 => 'Service class list empty',
        134 => 'Accumulator overflow',
        135 => 'Accumulator underflow',
        136 => 'Date adjustment error',
        137 => 'Get balance and date not allowed',
        138 => 'No PIN code registered',
        139 => 'Dedicated account not defined',
        140 => 'Invalid old Service Class',
        141 => 'Invalid language',
        142 => 'Subscriber already installed',
        143 => 'Invalid master subscriber',
        144 => 'Subscriber already activated',
        145 => 'Already linked subordinate',
        146 => 'Already linked as master',
        147 => 'Invalid old community list',
        148 => 'Invalid new community list',
        149 => 'Invalid promotion plan end date',
        150 => 'Invalid promotion plan allocation',
        151 => 'Promotion plan not found',
        152 => 'Deblocking of expired account',
        153 => 'Dedicated account max credit limit exceeded',
        154 => 'Invalid old SC date',
        155 => 'Invalid new service class',
        156 => 'Delete subscriber failed due to existing provider references',
        157 => 'Invalid account home region',
        158 => 'Not used',
        159 => 'Charged FaF not active for service class',
        160 => 'Operation not allowed from current location',
        161 => 'Failed to get location information',
        163 => 'Invalid dedicated account period',
        164 => 'Invalid dedicated account start date',
        165 => 'Offer not found',
        166 => 'Not used',
        167 => 'Invalid unit type',
        168 => 'Not used',

        // Refill Denied
        176 => 'Refill denied, First IVR call not made',
        177 => 'Refill denied, Account not active',
        178 => 'Refill denied, Service fee period expired',
        179 => 'Refill denied, Supervision period expired',

        // PAM Related (190–199)
        190 => 'PAM service id already exists',
        191 => 'PAM service id out of range or does not exist',
        192 => 'Old PAM class id incorrect',
        193 => 'Invalid PAM class id',
        194 => 'Old schedule id incorrect',
        195 => 'Invalid schedule id',
        196 => 'Invalid deferred to date',
        197 => 'Periodic account management evaluation failed',
        198 => 'Too many PAM services',
        199 => 'PAM period not found in schedule',

        200 => 'PAM class id does not exist',
        201 => 'Schedule id does not exist',
        202 => 'Invalid PAM indicator',
        203 => 'Subscriber installed but marked for deletion',
        204 => 'Account database inconsistency',
        205 => 'Max number of FaF indicators exceeded',
        206 => 'FaF indicator already exists',
        207 => 'Invalid accumulator end date',
        208 => 'Invalid accumulator service class',
        209 => 'Invalid dedicated account expiry date',
        210 => 'Invalid dedicated account service class',
        211 => 'Delete dedicated account failed',
        212 => 'Crop of composite dedicated account not allowed',
        213 => 'Sub dedicated account not defined',
        214 => 'Invalid or mismatched offer definition',
        215 => 'Too many Multi User Identification offers',
        216 => 'Usage threshold not found',
        217 => 'Usage counter not found',
        218 => 'Usage threshold does not exist on account',
        219 => 'Usage counter value out of bounds',
        220 => 'Value type does not match definition',
        221 => 'No subordinate subscribers connected',
        222 => 'Dedicated account cannot be deleted because it is in use',
        223 => 'New offer date incorrect',
        224 => 'Old offer date mismatch',
        225 => 'Offer start date cannot be changed',
        226 => 'Invalid PAM Period Relative Dates Start Indicator',
        227 => 'Invalid PAM Period Relative Dates Expiry Indicator',
        230 => 'Not allowed to convert lifetime type',
        232 => 'Not allowed to delete PAM service ID in use',
        233 => 'Invalid PAM Service Priority',
        234 => 'Old PAM service priority incorrect',
        235 => 'Not allowed to connect PAM Class to PAM Service',
        236 => 'PAM Service Priority already used',
        237 => 'Provider ID not allowed for this offer type',
        238 => 'Provider account offer requires Provider ID',
        239 => 'Time restriction does not exist',
        240 => 'End time before start time',
        241 => 'Timezone not found',
        242 => 'Discount not defined',
        243 => 'Missing associated party ID',
        244 => 'Associated party ID not allowed',
        245 => 'Provider owned usage counter cannot have personal threshold',
        246 => 'Common usage threshold does not exist',
        247 => 'Product not found',
        248 => 'Shared account offer not allowed on subordinate',
        249 => 'Invalid or missing product id',
        250 => 'Communication ID change failed: Insufficient funds',
        251 => 'Communication ID change failed: AIA/MSISDN mismatch',
        252 => 'Communication ID change failed: Invalid combination',
        253 => 'Communication ID change failed: Previous change pending',
        254 => 'Communication ID change failed: New MSISDN not available',
        255 => 'Operation not allowed on subordinate subscriber',
        256 => 'Attribute name does not exist',
        257 => 'Operation not allowed since End of Provisioning is set',
        258 => 'Attribute value does not exist',
        259 => 'Attribute value already exists',
        260 => 'Capability not available',
        261 => 'Invalid Capability combination',
        262 => 'Attribute update action not allowed',
        263 => 'Not used',
        264 => 'Nominal value out of bounds',
        265 => 'Too many Usage Accumulators',
        266 => 'Permission denied',
        267 => 'Backdate time out of range',
        268 => 'Backdate update not allowed',
        269 => 'Subscriber already marked for rerating',
        270 => 'Subscriber already unmarked for rerating',
        271 => 'Snapshot not found',
        272 => 'Unable to apply snapshot',
        273 => 'Operation not allowed on subscriber marked for rerating',
        274 => 'Invalid external Product Id',
        275 => 'Multiple providers not allowed',
        276 => 'Local provider does not exist',
        277 => 'Consumer configuration incompatible with local provider',
        278 => 'Operation not allowed for consumer connected to local provider',
        279 => 'Operation not allowed for local provider',
        280 => 'Rerating session mismatch',
        281 => 'Not allowed for multi user account',
        282 => 'Destination SDP ID does not exist in AF',
        283 => 'Target subscriber ID does not exist in AF',
        284 => 'Transfer failed, system inconsistency',
        285 => 'AF update failure, system inconsistency',
        286 => 'Incompatible SDP versions',
        287 => 'No transfer done, subscriber still in origin SDP',
        288 => 'Tree parameter name does not exist',
        289 => 'Tree parameter value wrong format',
        290 => 'Service provider does not exist',
        291 => 'Destination SDP not found',
        292 => 'Subscriber type not allowed for transfer',
        293 => 'Subscriber move failed, manual redirection removal required',
        294 => 'Cancel redirect failed, subscription not in redirection mode',
        295 => 'Subscription move failed, prohibited destination',
        296 => 'Tree parameter update action not allowed',
        297 => 'Maximum limit of offers exceeded during installation',
        298 => 'Failure to delete subscriber after failed offer installation',
        299 => 'Failure to install subscriber',
        300 => 'Product UCs on Products SharedOffers using associatedPartyID',
        301 => 'Predefined offer values not found',
        302 => 'Offer is not product capable',
        303 => 'Invalid parameters for scheduled tree parameter',
        304 => 'Subscriber movement failed, pending HLR update',
    ],

];