<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class () extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. If you are using PostgreSQL, we need a safe script loop to transform a text column into an identity integer sequence.
        // We handle this by dropping the original primary constraint, changing the type, and attaching a serial identity constraint.

        // Isolate your operations cleanly contextually
        Schema::table('catalog_products', function (Blueprint $table) {
            // Drop primary key constraints first to avoid database locking failures
            $table->dropPrimary();
        });

        // We alter the table schema using atomic SQL commands
        DB::statement('ALTER TABLE catalog_products ALTER COLUMN id TYPE INT USING (offer_id::integer)');
        DB::statement('ALTER TABLE catalog_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');

        Schema::table('catalog_products', function (Blueprint $table) {
            // Re-assign 'id' as the fresh integer primary tracking key
            $table->primary('id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('catalog_products', function (Blueprint $table) {
            $table->dropPrimary();
        });

        DB::statement('ALTER TABLE catalog_products ALTER COLUMN id DROP IDENTITY IF EXISTS');
        DB::statement('ALTER TABLE catalog_products ALTER COLUMN id TYPE VARCHAR(255)');

        Schema::table('catalog_products', function (Blueprint $table) {
            $table->primary('id');
        });
    }
};
